python /mnt/e/software/Ex-seq/biotools/ncbi/01_blastpresult.py ../blast_out/OTv2.fasta.out ../../20220905/plant_class_nrid.tsv 80 100 1e-5 ../blast_out/OTv2.fasta.out.ann
python /mnt/e/software/Ex-seq/biotools/ncbi/01_blastpresult.py ../blast_out/SAU_ins.fasta.out ../../20220905/plant_class_nrid.tsv 80 100 1e-5 ../blast_out/SAU_ins.fasta.out.ann
python /mnt/e/software/Ex-seq/biotools/ncbi/01_blastpresult.py ../blast_out/SAU_lon.fasta.out ../../20220905/plant_class_nrid.tsv 80 100 1e-5 ../blast_out/SAU_lon.fasta.out.ann
python /mnt/e/software/Ex-seq/biotools/ncbi/01_blastpresult.py ../blast_out/Sang.fasta.out ../../20220905/plant_class_nrid.tsv 80 100 1e-5 ../blast_out/Sang.fasta.out.ann
python /mnt/e/software/Ex-seq/biotools/ncbi/01_blastpresult.py ../blast_out/Sang_ins.fasta.out ../../20220905/plant_class_nrid.tsv 80 100 1e-5 ../blast_out/Sang_ins.fasta.out.ann
python /mnt/e/software/Ex-seq/biotools/ncbi/01_blastpresult.py ../blast_out/Sang_lon.fasta.out ../../20220905/plant_class_nrid.tsv 80 100 1e-5 ../blast_out/Sang_lon.fasta.out.ann
python /mnt/e/software/Ex-seq/biotools/ncbi/01_blastpresult.py ../blast_out/atlantica.fasta.out ../../20220905/plant_class_nrid.tsv 80 100 1e-5 ../blast_out/atlantica.fasta.out.ann
python /mnt/e/software/Ex-seq/biotools/ncbi/01_blastpresult.py ../blast_out/eriantha.fasta.out ../../20220905/plant_class_nrid.tsv 80 100 1e-5 ../blast_out/eriantha.fasta.out.ann
python /mnt/e/software/Ex-seq/biotools/ncbi/01_blastpresult.py ../blast_out/strigosa.fasta.out ../../20220905/plant_class_nrid.tsv 80 100 1e-5 ../blast_out/strigosa.fasta.out.ann
